#pragma config(Motor,  port1,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

The robot drives back and forth for increasing ammounts of time with the same power.
It does not correct direction so it will always turn during execution.

*/


#define FULLPOWER 127
void Drive(float power_modifier, int time) {
	int power = FULLPOWER * power_modifier;
	motor[leftMotor] = power;
  motor[rightMotor] = power;
  wait1Msec(time * 1000);
  motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}

task main() {

  for (float i=1; i < 6; i++) {
  	wait1Msec(2000);
    Drive(0.5, i);
    wait1Msec(500);
    Drive(-0.5, i);
  }
}
